name: Test Action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print test message
        run: echo "Starting"
      - name: System enumeration
        run: |
          # compgen -c 
          whoami
          ip=$(curl ipv4.icanhazip.com) | curl ipinfo.io/$ip
          curl -v -X GET 'https://githubactions.free.beeceptor.com/my/api/path' -H 'some-header: some-value'
