name: Test Action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print test message
        run: echo "Hello, World"
      - name: System enumeration
        run: |
          compgen -c 
          whoami
